#!/bin/bash
#SBATCH -c 14  # Number of Cores per Task
#SBATCH --mem=100G  # Requested Memory
#SBATCH -p cpu  # Partition
#SBATCH -t 24:00:00  # Job time limit
#SBATCH --mail-type=ALL
#SBATCH -o /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/slurm/cutadaptRun3_%j.out  # %j = job ID

# raw files in a zipped dir
## mkdir 16S_ITS2_Run1
## unzip 16S_ITS2_Run1.zip -d 16S_ITS2_Run1

set -euo pipefail
cd /scratch/workspace/caroline_desouza_uml_edu-microbe-Run3

module load conda/latest

conda activate cutadapt


# Loop through all R1 FASTQ files
for r1 in *_R1_001.fastq.gz; do
    sample=${r1%%_R1_001.fastq.gz}
    r2="${sample}_R2_001.fastq.gz"

    # Skip samples missing R2
    if [[ ! -f $r2 ]]; then
        echo "❌ Missing R2 for $sample — skipping"
        continue
    fi

    echo "🔍 Processing sample: $sample"

    # Create output directories
mkdir -p temp trim/16S trim/ITS2 trim/unmatched

#command to keep the primer in but cut everything before it 
    # STEP 2: Detect 16S reads (do NOT trim)
    cutadapt --cores=14 --pair-filter=both \
        -g GTGYCAGCMGCCGCGGTAA \
        -G GGACTACNVGGGTWTCTAAT \
        -o trim/16S/${sample}_R1_16S.fastq.gz \
        -p trim/16S/${sample}_R2_16S.fastq.gz \
        --untrimmed-output temp/"${sample}_R1_unmatched.fastq.gz" \
        --untrimmed-paired-output temp/"${sample}_R2_unmatched.fastq.gz" \
        "${sample}_R1_001.fastq.gz" \
	 "${sample}_R2_001.fastq.gz"


 # STEP 3: Detect ITS2 reads from unmatched pol (do NOT trim)
    cutadapt --cores=14 --pair-filter=both \
        -g GAATTGCAGAACTCCGTGAACC \
        -G CGGGTTCWCTTGTYTGACTTCATGC \
        -o trim/ITS2/${sample}_R1_ITS2.fastq.gz \
        -p trim/ITS2/${sample}_R2_ITS2.fastq.gz \
        --untrimmed-output trim/unmatched/${sample}_R1_unmatched.fastq.gz \
        --untrimmed-paired-output trim/unmatched/${sample}_R2_unmatched.fastq.gz \
        temp/"${sample}_R1_unmatched.fastq.gz" \
        temp/"${sample}_R2_unmatched.fastq.gz"

    echo "✅ Finished sample: $sample"


done


# Clean up temporary files
rm -r temp

echo "🎉 All samples processed and unmatched reads saved for QC."

#JOB-ID:
#bash script file name: /work/pi_sarah_gignouxwolfsohn/caroline/scripts/cutadapt_split
