#!/bin/bash
#SBATCH -c 17  # Number of Cores per Task
#SBATCH --mem=180G  # Requested Memory
#SBATCH -p cpu  # Partition
#SBATCH --qos=long
#SBATCH -t 120:00:00  # Job time limit
#SBATCH --mail-type=ALL
#SBATCH -o /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/slurm/run2-dada2-%j.out  # %j = job ID


# Activate conda and the correct environment
cd /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline

module load conda/latest
conda activate /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/dada2

# Move to working directory
cd /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline


# Path to R script
rscript="/work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/dada2.r"

# Run R script
Rscript "$rscript"
