#!/bin/bash
#SBATCH -c 5  # Number of Cores per Task
#SBATCH --mem=100G  # Requested Memory
#SBATCH -p cpu  # Partition
#SBATCH -t 7:00:00  # Job time limit
#SBATCH --mail-type=ALL
#SBATCH -o /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/slurm/slurm_pair_fastqc-%j.out  # %j = job ID

#fastqc env
cd /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/envs

module load conda/latest

conda activate ./fastqc


#where to find the sequence files
cd /scratch4/workspace/caroline_desouza_uml_edu-microbe-Run2/trim/16S/R2

fastqc -o /scratch4/workspace/caroline_desouza_uml_edu-microbe-Run2/trim/16S/fastqc/R2  /scratch4/workspace/caroline_desouza_uml_edu-microbe-Run2/trim/16S/R2/*.fastq


# R1_job ID: 51214094

# R2_job ID: 51214917
