#!/bin/bash
#SBATCH -c 5  # Number of Cores per Task
#SBATCH --mem=100G  # Requested Memory
#SBATCH -p cpu  # Partition
#SBATCH -t 7:00:00  # Job time limit
#SBATCH --mail-type=ALL
#SBATCH -o /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/slurm/run5R2_multiqc-%j.out  # %j = job ID

#now working with multiqc
cd /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/envs/

module load conda/latest
conda activate /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/envs/multiqc
multiqc --version

#set dir

#where to find the html files R1
cd /scratch4/workspace/caroline_desouza_uml_edu-microbe-Run1/16S_ITS2_Run5/16S_trim/fastqc

multiqc -o /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/BEL_16S_ITS2/qc_reports /scratch4/workspace/caroline_desouza_uml_edu-microbe-Run1/16S_ITS2_Run5/16S_trim/fastqc/R2/*



# R1_job ID:51214909
# R2_job ID: 51215023
