#!/bin/bash
#SBATCH -c 4  # Number of Cores per Task
#SBATCH --mem=180G  # Requested Memory
#SBATCH -p cpu  # Partition
#SBATCH -t 12:00:00  # Job time limit
#SBATCH --mail-type=ALL
#SBATCH -o /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/slurm/slurm-dada2_trim-%j.out  # %j = job ID


# Activate conda and the correct environment
cd /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline

module load conda/latest
conda activate /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline/dada2

# Move to working directory
cd /work/pi_sarah_gignouxwolfsohn_uml_edu/caroline

# Run the notebook
papermill ./old_16S_notebooks/trim_cutadapt_16S_dada2.ipynb --autosave-cell-every 20
